### ISSUE TITLE
Error with 12th Class result calculation

### ISSUE THREAD

**Issue by AviaAlex2012** [PrathamGupta06/CBSE-result-parser#1]
While running the file for class 12 result the output stops with error
Enter Input Result File Path (e.g demo/12th.txt): 50710(5).txt
Enter Output Path (e.g 12th.xlsx): ResultT.xlsx
Enter Class (10th or 12th): 12th
Found 163 students.
Traceback (most recent call last):
  File "E:\CBSE\main.py", line 79, in <module>
    headers, data, AllSubjectNames = get_data(input_file, mode)
  File "E:\CBSE\functions.py", line 487, in get_data
    return get_data_12th(result_file)
  File "E:\CBSE\functions.py", line 524, in get_data_12th
    headers, unique_subject_names = get_headers(unique_subject_codes, mode)
  File "E:\CBSE\functions.py", line 428, in get_headers
    unique_subject_names = convert_codes_to_subjects(unique_subject_codes, mode)
  File "E:\CBSE\functions.py", line 255, in convert_codes_to_subjects
    return [CBSE_CLASS_12_SUBJECT_CODES[code] for code in list_of_codes]
  File "E:\CBSE\functions.py", line 255, in <listcomp>
    return [CBSE_CLASS_12_SUBJECT_CODES[code] for code in list_of_codes]
**KeyError: '241'**

**Comment by AviaAlex2012** [comment]
Some subjects are missing in list in my case it was 241 Applied mathematics, add the subjects and the error is gone

**Comment by AviaAlex2012** [comment]
Some subjects are missing in list in my case it was 241 Applied mathematics, add the subjects and the error is gone

**Comment by PrathamGupta06** [comment]
Hi, were there any other subjects missing except for 241?

**Comment by AviaAlex2012** [comment]
> Hi, were there any other subjects missing except for 241?

Yes I can send you the details by email if you need else you may download the list of updated subjects from CBSE website. Better let the users update the list by themselves in functions.py file
